PetitesPuces/PetitesPuces/Controllers/BDController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using PetitesPuces.Models;

namespace PetitesPuces.Controllers
{
    public class BDController : Controller
    {
        // GET: BD
        public ActionResult Index()
        {
            if (Session["gestionnaireObj"] != null)
            {

                ViewModels.XmlDataViewModel model = new ViewModels.XmlDataViewModel();
                DataClasses1DataContext context = new DataClasses1DataContext();

                context.Connection.ConnectionString = Properties.Settings.Default.BD6B8_424R_TESTSConnectionString;
                try
                {
                    context.Connection.Open();
                    model.tabCount = GetTableCount(context, true);
                    setBtnStatus(model);
                    model.tabCount = GetTableCount(context, model.enableDeleteButton);

                }
                catch (Exception ex)
                {
                    model.errorMessage = ex.Message;
                }

                context.Connection.Close();
                return View(model);
            }
            else return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }

        //Insert
        [HttpPost]
        public ActionResult Ajouter(ViewModels.XmlDataViewModel model)
        {
            if (Session["gestionnaireObj"] == null) return View("Index", model);

            List<PPClients> lstClients = new List<PPClients>();
            List<PPVendeurs> lstVendeurs = new List<PPVendeurs>();
            List<PPProduits> lstProduits = new List<PPProduits>();

            List<PPDetailsCommandes> lstDetailsCommandes = new List<PPDetailsCommandes>();
            List<PPCommandes> lstCommandes = new List<PPCommandes>();
            List<PPArticlesEnPanier> lstArticlesEnPanier = new List<PPArticlesEnPanier>();
            List<PPHistoriquePaiements> lstHistoriquePaiements = new List<PPHistoriquePaiements>();

            List<PPCategories> lstCategories = new List<PPCategories>();
            List<PPVendeursClients> lstVendeursClients = new List<PPVendeursClients>();
            List<PPGestionnaire> lstGestionnaire = new List<PPGestionnaire>();
            List<PPTaxeFederale> lstTaxeFederale = new List<PPTaxeFederale>();
            List<PPTaxeProvinciale> lstTaxeProvinciale = new List<PPTaxeProvinciale>();
            List<PPTypesLivraison> lstTypesLivraison = new List<PPTypesLivraison>();
            List<PPTypesPoids> lstTypesPoids = new List<PPTypesPoids>();
            List<PPPoidsLivraisons> lstPoidsLivraisons = new List<PPPoidsLivraisons>();


            XDocument doc = XDocument.Load(HostingEnvironment.MapPath("~/Content/fichierXML.xml"));
            XNamespace ss = "urn:schemas-microsoft-com:office:spreadsheet";

            foreach (var v in doc.DescendantNodes())
            {
                XElement elem = v.NextNode as XElement;

                if (elem?.Name == ss + "Workbook") //Workbook
                {
                    var workSheets = elem?.Elements().Where(t => t.Name == ss + "Worksheet");
                    if (workSheets == null) return View();

                    foreach (var sheet in workSheets)
                    {
                        var tables = sheet.Elements().Where(n => n.Name == ss + "Table");
                        foreach (var table in tables)
                        {

                            /*
                             *   Table PPClients
                             */
                            if (sheet.Attribute(ss + "Name").Value == "PPClients")
                            {
                                var tabObjs = GetTableCellStrings(table);
                                foreach (var obj in tabObjs)
                                {
                                    if (obj[0] != null)
                                    {
                                        lstClients.Add(new PPClients()
                                        {
                                            NoClient = CheckLong(obj[0]),
                                            AdresseEmail = obj[1],
                                            MotDePasse = obj[2],
                                            Nom = obj[3],
                                            Prenom = obj[4],
                                            Rue = obj[5],
                                            Ville = obj[6],
                                            Province = obj[7],
                                            CodePostal = obj[8],
                                            Pays = obj[9],
                                            Tel1 = obj[10],
                                            Tel2 = obj[11],
                                            DateCreation = CheckDate(obj[12]),
                                            DateMAJ = CheckDate(obj[13]),
                                            NbConnexions = CheckShort(obj[14]),
                                            DateDerniereConnexion = CheckDate(obj[15]),
                                            Statut = CheckShort(obj[16])
                                        });
                                    }
                                }
                            }


                            /*
                             *   Table PPVendeurs
                             */
                            if (sheet.Attribute(ss + "Name").Value == "PPVendeurs")
                            {
                                var tabObjs = GetTableCellStrings(table);
                                foreach (var obj in tabObjs)
                                {
                                    if (obj[0] != null)
                                    {
                                        lstVendeurs.Add(new PPVendeurs()
                                        {
                                            NoVendeur = CheckLong(obj[0]),
                                            NomAffaires = obj[1],
                                            Nom = obj[2],
                                            Prenom = obj[3],
                                            Rue = obj[4],
                                            Ville = obj[5],
                                            Province = obj[6],
                                            CodePostal = obj[7],
                                            Pays = obj[8],
                                            Tel1 = obj[9],
                                            Tel2 = obj[10],
                                            AdresseEmail = obj[11],
                                            MotDePasse = obj[12],
                                            PoidsMaxLivraison = CheckInt(obj[13]),
                                            LivraisonGratuite = CheckDecimal(obj[14]),
                                            Taxes = CheckInt(obj[15]) == 1,
                                            Pourcentage = CheckDecimal(obj[16]),
                                            Configuration = obj[17],
                                            DateCreation = CheckDate(obj[18]),
                                            DateMAJ = CheckDate(obj[19]),
                                            Statut = CheckShort(obj[20])
                                        });
                                    }
                                }
                            }


                            /*
                             *   Table PPProduits
                             */
                            if (sheet.Attribute(ss + "Name").Value == "PPProduits")
                            {
                                var tabObjs = GetTableCellStrings(table);
                                foreach (var obj in tabObjs)
                                {
                                    if (obj[0] != null)
                                    {
                                        lstProduits.Add(new PPProduits()
                                        {
                                            NoProduit = CheckLong(obj[0]),
                                            NoVendeur = CheckLong(obj[1]),
                                            NoCategorie = CheckInt(obj[2]),
                                            Nom = obj[3],
                                            Description = obj[4],
                                            Photo = obj[5],
                                            PrixDemande = CheckDecimal(obj[6]),
                                            NombreItems = CheckShort(obj[7]),
                                            Disponibilité = CheckInt(obj[8]) == 1,
                                            DateVente = CheckDate(obj[9]),
                                            PrixVente = CheckDecimal(obj[10]),
                                            Poids = CheckDecimal(obj[11]),
                                            DateCreation = CheckDate(obj[12]),
                                            DateMAJ = CheckDate(obj[13])
                                        });
                                    }
                                }
                            }


                            /*
                             *   Table PPDetailsCommandes
                             */
                            if (sheet.Attribute(ss + "Name").Value == "PPDetailsCommandes")
                            {
                                var tabObjs = GetTableCellStrings(table);
                                foreach (var obj in tabObjs)
                                {
                                    if (obj[0] != null)
                                    {

PetitesPuces/PetitesPuces/Views/BD/Index.cshtml
@model PetitesPuces.ViewModels.XmlDataViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Jeu d'essai</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="container mt-5 mb-5">
        <table class="table table-sm table-striped">
            <tr class="row">
                <th class="col-6">
                    @using (Html.BeginForm("Ajouter", "BD", FormMethod.Post))
                    {
                        <input type="submit" class="btn btn-block btn-success" value="Ajouter les données" disabled="@(!Model.enableAddButton)">
                    }
                </th>
                <th class="col-6">
                    @using (Html.BeginForm("Retirer", "BD", FormMethod.Post))
                    {
                        <input type="submit" class="btn btn-block btn-danger" value="Retirer les données" disabled="@(!Model.enableDeleteButton)">
                    }
                </th>
            </tr>
            <tr class="row mt-3 text-center">
                <td class="col-12 text-white bg-success">
                    @Html.DisplayTextFor(m => m.successMessage)
                </td>
            </tr>
            <tr class="row mt-3 text-center">
                <td class="col-12 text-dark bg-warning">
                    @Html.DisplayTextFor(m => m.errorMessage)
                </td>
            </tr>
            @{
                for (int i = 0; i < (Model.tabCount.Length) / 2; i++)
                {
                    <tr class="row">
                        <td class="col-6 text-right"> @Model.tabCount[i, 0] : </td>
                        <td class="col-6 text-left"><b>@Model.tabCount[i, 1]</b> enregistrement(s)</td>
                    </tr>
                }
            }
        </table>
        @Html.ActionLink("Retour à l'accueil", "AccueilGestionnaire", "Gestionnaire", new object {  }, new { @class = "btn btn-block btn-primary" })
    </div>
</body>
</html>