PetitesPuces/PetitesPuces/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetitesPuces.Models;
using PagedList;
using System.Transactions;
using System.Globalization;
using System.IO;
using System.Text;
using System.Web.UI;
using ExpertPdf.HtmlToPdf;
using PetitesPuces.Filter;

namespace PetitesPuces.Controllers
{
    [VerifieSessionClient]
    public class ClientController : Controller
    {
        DataClasses1DataContext contextPP = new DataClasses1DataContext();
        ClientDao clientDao;
        public string RenderToString(PartialViewResult partialView)
        {
            var view = ViewEngines.Engines.FindPartialView(ControllerContext, partialView.ViewName).View;

            var sb = new StringBuilder();
            using (var sw = new StringWriter(sb))
            {
                using (var tw = new HtmlTextWriter(sw))
                {
                    view.Render(new ViewContext(ControllerContext, view, partialView.ViewData, partialView.TempData, tw), tw);
                }
            }

            return sb.ToString();
        }

        public ActionResult Index()
        {
            return RedirectToAction("AccueilClient");
        }


        public ActionResult HistoriqueCommande()
        {
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            var lstCommandes = (from commande in db.GetTable<PPCommandes>()
                                where commande.NoClient.Equals(((PPClients)Session["clientObj"]).NoClient)
                                orderby commande.DateCommande descending
                                select commande
                                ).ToList();

            return View(lstCommandes);
        }

        
        public ActionResult AccueilClient()
        {
            //GestionAccesClient()

            List<Models.EntrepriseCategorie> lstEntreCate = new List<Models.EntrepriseCategorie>();
            String noClient = ((PPClients)Session["clientObj"]).NoClient.ToString();

            //long noClient = ((Models.PPClients)Session["clientObj"]).NoClient;
            /* Compare data with Database */
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();

            //Requête qui va permettre d'aller chercher les paniers du client
            var paniers = (from panier in contextPP.GetTable<Models.PPArticlesEnPanier>()
                           where panier.NoClient.Equals(noClient) && 0 <= panier.PPProduits.NombreItems
                           group panier by panier.PPVendeurs);
            var toutesCategories = (from cat in db.GetTable<Models.PPCategories>()
                                    select cat
                                 );
            foreach (var cat in toutesCategories)
            {
                List<PPVendeurs> lstVendeurs = new List<PPVendeurs>();
                var query = (from prod in db.GetTable<Models.PPProduits>()
                             where prod.NoCategorie.Equals(cat.NoCategorie)
                             select prod
                             );
                foreach (var item in query)
                {
                    if (!lstVendeurs.Contains(item.PPVendeurs))
                    {
                        lstVendeurs.Add(item.PPVendeurs);
                    }
                }
                lstEntreCate.Add(new Models.EntrepriseCategorie(cat, lstVendeurs));
            }

            AccueilClientViewModel items = new AccueilClientViewModel(lstEntreCate, paniers);

            db.Connection.Close();

            return View(items);
        }


        public ActionResult EnvoyerMessage(int noDestinataire, int noExpediteur, string message)
        {
            if (message.Trim().Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            else
            {
                Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
                db.Connection.Open();
                int noMessages = 1;
                //Aller chercher le dernier noMessage
                var messages = (from msg in db.GetTable<PPMessages>()
                                group msg by true into r
                                select new
                                {
                                    max = r.Max(max => max.NoMsg)
                                }
                                ).ToList();
                if (messages.Count() > 0)
                {
                    noMessages = messages.First().max + 1;
                }

                //Ajouter un message
                PPMessages ppMessage = new PPMessages
                {
                    NoMsg = noMessages,
                    NoExpediteur = noExpediteur,
                    DescMsg = message,
                    FichierJoint = null,
                    Lieu = 2,
                    dateEnvoi = DateTime.Now,
                    objet = "Question sur un de vos produit"
                };
                //Ajouter un Destinataire
                PPDestinataires ppDestinataires = new PPDestinataires
                {
                    NoMsg = noMessages,
                    NoDestinataire = noDestinataire,
                    EtatLu = 0,
                    Lieu = 1
                };

                //Ajouter les nouveaux objets à leur collection
                db.PPMessages.InsertOnSubmit(ppMessage);
                db.PPDestinataires.InsertOnSubmit(ppDestinataires);

                // Submit the change to the database.
                try
                {
                    db.SubmitChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
                db.Connection.Close();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
        }


        // GET: Client
        public ActionResult SaisieCommande(SaisieCommandeViewModel sViewModelParam)
        {
            List<Province> lstProvinces = new List<Province>
            {
                new Province { Abreviation = "NB", Nom = "Nouveau-Brunswick"},
                new Province { Abreviation = "ON", Nom = "Ontario"},
                new Province { Abreviation = "QC", Nom = "Québec"},
            };

            ViewBag.ListeProvinces = new SelectList(lstProvinces, "Abreviation", "Nom");


            List<PPArticlesEnPanier> items = new List<PPArticlesEnPanier>();
            List<PPArticlesEnPanier> lstItemsARetirer = new List<PPArticlesEnPanier>();

            items = (from panier in contextPP.GetTable<Models.PPArticlesEnPanier>()
                     where panier.NoClient.Equals(sViewModelParam.client.NoClient) && panier.NoVendeur.Equals(sViewModelParam.vendeur.NoVendeur) &&
                     panier.PPProduits.NombreItems > 0 && panier.PPProduits.Disponibilité == true
                     select panier).ToList();
            lstItemsARetirer = (from panier in contextPP.GetTable<Models.PPArticlesEnPanier>()
                                where panier.NoClient.Equals(sViewModelParam.client.NoClient) && panier.NoVendeur.Equals(sViewModelParam.vendeur.NoVendeur) &&
                                (panier.PPProduits.NombreItems <= 0 || panier.PPProduits.Disponibilité == false)
                                select panier).ToList();


            contextPP.GetTable<PPArticlesEnPanier>().DeleteAllOnSubmit(lstItemsARetirer);
            contextPP.SubmitChanges();
            foreach (PPArticlesEnPanier ppPan in items)
            {
                if (ppPan.NbItems > ppPan.PPProduits.NombreItems)
                {
                    contextPP.GetTable<PPArticlesEnPanier>().Where(p => p.NoProduit == ppPan.NoProduit).First().NbItems = ppPan.PPProduits.NombreItems;
                    contextPP.SubmitChanges();
                }
            }
            items = (from panier in contextPP.GetTable<Models.PPArticlesEnPanier>()
                     where panier.NoClient.Equals(sViewModelParam.client.NoClient) && panier.NoVendeur.Equals(sViewModelParam.vendeur.NoVendeur) &&
                     panier.PPProduits.NombreItems > 0 && panier.PPProduits.Disponibilité == true
                     select panier).ToList();
            if (items == null || items.Count == 0)
            {
                List<EntrepriseCategorie> lstEntreCate = new List<EntrepriseCategorie>();
                //Requête qui va permettre d'aller chercher les paniers du client
                var paniers = from panier in contextPP.GetTable<Models.PPArticlesEnPanier>()
                              where panier.NoClient.Equals(sViewModelParam.client.NoClient)
                              group panier by panier.PPVendeurs;
                var toutesCategories = (from cat in contextPP.GetTable<Models.PPCategories>()
                                        select cat
                                     );
                foreach (var cat in toutesCategories)
                {
                    List<PPVendeurs> lstVendeurs = new List<PPVendeurs>();
                    var query = (from prod in contextPP.GetTable<Models.PPProduits>()
                                 where prod.NoCategorie.Equals(cat.NoCategorie)
                                 select prod
                                 );
                    foreach (var obj in query)
                    {
                        if (!lstVendeurs.Contains(obj.PPVendeurs))
                        {
                            lstVendeurs.Add(obj.PPVendeurs);
                        }
                    }
                    lstEntreCate.Add(new Models.EntrepriseCategorie(cat, lstVendeurs));
                }

                AccueilClientViewModel item = new AccueilClientViewModel(lstEntreCate, paniers);

PetitesPuces/PetitesPuces/Views/Shared/Client/Categories.cshtml
@using PetitesPuces.Models
@model List<EntrepriseCategorie>

@{ 
   int compteur = 0;
   DataClasses1DataContext db = new DataClasses1DataContext();
   db.Connection.Open();
   Dictionary<int, List<int>> dicNombreProduits = new Dictionary<int, List<int>>();

   foreach(var cat in Model)
   {
      List<int> nombreProduits = new List<int>();
      foreach(var vendeur in cat.lstVendeurs)
      {

         var query = (from nbProduit in db.GetTable<PPProduits>()
                      where (nbProduit.NoCategorie.Equals(cat.categorie.NoCategorie)) && (nbProduit.NoVendeur.Equals(vendeur.NoVendeur))
                      select nbProduit
                      ).ToList();
         nombreProduits.Add(query.Count());
      }
      dicNombreProduits.Add(cat.categorie.NoCategorie, nombreProduits);
   }
}

<div id="accordion">
   @foreach (var entrepriseCat in Model)
   {
      if (entrepriseCat.lstVendeurs.Count > 0)
      {
         <div class="card mt-2">
            <div class="card-header" id="headingCat_@entrepriseCat.categorie.NoCategorie">
               <div class="float-left">
                  <img src="~/Content/images/categorie.jpg" alt="panier" class="rounded-circle" height="50px" width="50px">
               </div>

               <div class="float-center">
                  <h5 class="mb-0">
                     <button class="btn btn-link" data-toggle="collapse" data-target="#collapseCat_@entrepriseCat.categorie.NoCategorie" aria-expanded="true" aria-controls="collapseCat_@entrepriseCat.categorie.NoCategorie">
                        @entrepriseCat.categorie.Description
                     </button>
                  </h5>
               </div>
            </div>

            <div id="collapseCat_@entrepriseCat.categorie.NoCategorie" class="collapse" aria-labelledby="headingCat_@entrepriseCat.categorie.NoCategorie" data-parent="#accordion">

               <div class="card-body">
                  <div class="row">
                     @{
                        int compteurj = 0;
                     }
                     @foreach (var entreprises in entrepriseCat.lstVendeurs)
                     {
                        <div class="col-sm-3">
                           <div class="card">
                              <div class="card-header">
                                 <h5>@entreprises.NomAffaires (@dicNombreProduits.ElementAt(compteur).Value.ElementAt(compteurj))</h5>
                              </div>
                              <div class="card-body">
                                 <div class="float-center">
                                    <img src="~/Content/images/icon.png" alt="entreprise" width="75px" height="75px" class="rounded-circle">
                                 </div>
                              </div>
                              <div class="card-footer">
                                 @{
                                    if ((PPClients)Session["clientObj"] != null)
                                    {
                                       @Html.ActionLink("Voir l'entreprise", "Catalogue", "Client", new { vendeur = entreprises.NomAffaires, categorie = entrepriseCat.categorie.Description }, new { @class = "btn btn-success" })
                                    }
                                    else
                                    {
                                       @Html.ActionLink("Voir l'entreprise", "CatalogueNouveaute", "Internaute", new { @class = "btn btn-success" })
                                    }
                                 }
                                 <!--<button id="btn_@entreprises.NoVendeur" class="btn btn-success">Voir l'entreprise</button>-->
                              </div>
                           </div>
                        </div>
                        compteurj++;
                     }
                  </div>
               </div>
            </div>
         </div>
         <hr />
      }
      compteur++;
   }
</div>

PetitesPuces/PetitesPuces/Views/Shared/Client/DetailProduit.cshtml
@using PetitesPuces.ViewModels
@model ProduitDetailViewModel
@{
    double dblPrixDemande = (double)Model.Produit.PrixDemande;
}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">@Model.Produit.Nom</h3>
        <div class="d-flex justify-content-between">
            <small>#@Model.Produit.NoProduit</small>
            <span class="badge badge-success" style="font-size: 15px;">@Model.Produit.PPCategories.Description</span>
        </div>
    </div>
    <div class="card-body">
        <div class="media">
            <div class="media-left">
                <img class="media-object m-2" src="~/Content/images/@Model.Produit.Photo" alt="produit ...."
                     style="max-width: 30rem; min-width: 20rem; max-height: 30rem; min-height: 20rem;">
            </div>
            <div class="media-body">
                <p>
                    <h1 id="spPrix">
                        @dblPrixDemande.ToString("0.00") $

                        @if (Model.Produit.DateVente.HasValue && DateTime.Now <= Model.Produit.DateVente.Value)
                        {
                            <span class="badge badge-warning">Promotion</span>
                        }

                    </h1>
                    @if (Model.Produit.DateVente.HasValue && DateTime.Now <= Model.Produit.DateVente.Value)
                    {
                        var rabais = Model.Produit.PrixDemande - Model.Produit.PrixVente;
                        <small>rabais de @rabais.Value.ToString("0.00")$</small><br />
                        <small>jusqu'au @Model.Produit.DateVente.Value.ToString("yyyy-MM-dd")</small><br />
                    }

                    @if (Session["clientObj"] != null)
                    {
                        <span><span class="font-weight-bold">Vendu par:</span> <a href="@Url.Action("Catalogue", "Client", new { vendeur = @Model.Produit.PPVendeurs.NomAffaires})">@Model.Produit.PPVendeurs.NomAffaires</a></span>
                    }
                    else
                    {
                        <span><span class="font-weight-bold">Vendu par:</span> @Model.Produit.PPVendeurs.NomAffaires</span>
                    }

                    <br />
                    @{
                        var sansDecimal = Model.FormattedRating - (Model.FormattedRating % 1);

                        for (var i = 1; i <= 5; i++)
                        {
                            if (i <= sansDecimal)
                            {
                                <span class="fa fa-star checked"></span>
                            }
                            else if (i <= sansDecimal + 1 && Model.FormattedRating % 1 != 0)
                            {
                                <i class="fas fa-star-half-alt checked"></i>
                            }
                            else
                            {
                                <span class="far fa-star checked"></span>
                            }
                        }
                    }
                    <span>
                        <small class="badge badge-pill badge-warning">@Model.FormattedRating.ToString("F1")</small>
                        &nbsp;&nbsp;&nbsp;
                        <span class="badge badge-pill badge-primary">@Model.nbEvaluateurs commentaire@(Model.nbEvaluateurs != 1 ? "s" : "")</span>
                    </span>
                </p>
                <hr>
                <p>
                    @if (Session["clientObj"] != null)
                    {
                        <button type="button" class="btn btn-outline-primary" value="@Model.Produit.NoProduit" onclick="$.VerificationDisponibilite(this.value)" @(Model.Produit.NombreItems == 0 ? "disabled" : "")>Ajouter au panier <span class="fas fa-shopping-cart"></span></button>
                    }

                    @if (Model.Produit.NombreItems > 0)
                    {
                        <span id="spQqt">Quantité restant: @Html.DisplayFor(x => Model.Produit.NombreItems)</span>
                    }
                    else if (Model.Produit.NombreItems <= 0)
                    {
                        <span id="spQqt">Quantité restant: <span class="badge badge-danger">Rupture de stock</span></span>
                    }

                    @if (Session["clientObj"] != null)
                    {
                        <br /><br /><button id="btn_envoyer_message" class="btn btn-outline-primary" onclick="accepter(@Model.Produit.NoVendeur);">Contacter le vendeur</button>
                    }
                </p>
                <hr>
                <p class="font-weight-bold">Description:</p>
                <p style="word-break:break-word; white-space:normal;">@Model.Produit.Description</p>
                <p>
                    <span class="font-weight-bold">Poids:</span><span> @Model.Produit.Poids lb</span><br />
                    <span><span class="font-weight-bold">En vente depuis:</span> @Model.Produit.DateCreation.Value.ToString("yyyy-MM-dd")</span>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="modAjoutPanier" aria-hidden="true" style="z-index:1072;">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ajout au panier</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p style="color:red; display:none;" id="messageAvertissement">
                    Attention! Le produit est déjà <br /><span id="spQuantite"></span> fois dans votre panier!
                </p>
                <p style="color:red; display:none;" id="messageIndisponible">
                    L'inventaire ne permet pas de commander plus de ce produit!
                </p>
                <div class="d-flex" id="divControleQuantite">
                    <label for="numNbAjoutPanier" class="col-form-label mr-auto">Quantité: </label>
                    <input id="numNbAjoutPanier" type="number" class="form-control col-5" min="1" step="1" value="1" onKeyUp="if (!Number.isInteger(Number(this.value))) { this.value = '';  } else if (Number(this.value) > Number(this.max)) { this.value = ''; } else if (Number(this.value) < 1) { this.value = '';}" />
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnAjoutProduit" type="button" class="btn btn-outline-success" value="@Model.Produit.NoProduit" onclick="$.AjoutAuPanier(this.value)">Ajouter</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

PetitesPuces/PetitesPuces/Views/Shared/Client/PanierAccueil.cshtml
@using PetitesPuces.Models
@model AccueilClientViewModel
<div class="row">
   <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
      @{
         DataClasses1DataContext db = new DataClasses1DataContext();
         db.Connection.Open();

         var client = (from c in db.GetTable<PPClients>()
                       where c.NoClient.Equals(((PPClients)Session["clientObj"]).NoClient)
                       select c
                       ).ToList();

         if (Model.lstPanierVendeur.Count() > 0)
         {
            <h4>Les paniers</h4>
         }
      }

      <ul class="nav nav-pills flex-column">
         @{
            int compteur = 1;
            foreach (var item in Model.lstPanierVendeur)
            {
               <li class="nav-item">
                  <a class="nav-link" href="#heading_@item.Key.NoVendeur">Panier @item.Key.NomAffaires<span class="sr-only">(current)</span></a>
               </li>
               compteur++;
            }
            <h3>Catégories</h3>
            foreach (var item in Model.lstEntreCategories)
            {
               if (item.lstVendeurs.Count() > 0)
               {
                  <li class="nav-item">
                     <a class="nav-link" href="#headingCat_@item.categorie.NoCategorie">@item.categorie.Description<span class="sr-only">(current)</span></a>
                  </li>
               }
            }
         }
      </ul>
   </nav>

    <!--Les catégories avec entreprises-->
   <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
      <hr>
      <h3>Bienvenue @client.First().Prenom @client.First().Nom!</h3>
      <hr />
      @{
         if (Model.lstPanierVendeur.Count() > 0)
         {
            <h4>Voici vos paniers</h4>
         }
         else
         {
            <h4>Vous n'avez pas de panier pour l'instant</h4>
            <br />
            <hr />
         }
      }

      <div id="accordionPanier">
         @foreach (var articlesVendeur in Model.lstPanierVendeur)
         {
            <div class="card">
               <div class="card-header" id="heading_@articlesVendeur.Key.NoVendeur">
                  <div class="float-left">
                     <img src="~/Content/images/cart.jpg" alt="panier" class="rounded-circle" height="50px width="50px">
                  </div>
                  <div class="float-center">
                     <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapse_@articlesVendeur.Key.NoVendeur" aria-expanded="true" aria-controls="collapse_@articlesVendeur.Key.NoVendeur">
                           @articlesVendeur.Key.NomAffaires
                        </button>
                     </h5>
                  </div>
               </div>

               <div id="collapse_@articlesVendeur.Key.NoVendeur" class="collapse" aria-labelledby="heading_@articlesVendeur.Key.NoVendeur" data-parent="#accordionPanier">

                  <div class="card-body">
                     <div class="card">
                        <div class="card-header">
                           <h4>@articlesVendeur.Key.NomAffaires</h4>
                        </div>
                        <div class="card-body">
                           <div class="row">
                              @foreach (var article in articlesVendeur)
                              {
                                 double dblPrixVente = (double)article.PPProduits.PrixDemande;
                                 <div class="col-sm-2">
                                    <div class="card">
                                       <div class="card-header">
                                          <h5>@article.PPProduits.Nom</h5>
                                       </div>
                                       <div class="card-body">
                                          <div class="float-center">
                                             <img src="~/Content/images/@article.PPProduits.Photo" alt="" width="125px" height="125px" class="rounded-circle">
                                          </div>
                                       </div>
                                       <div class="card-footer">
                                          <h5>@dblPrixVente.ToString("0.00") $</h5>
                                       </div>
                                    </div>
                                 </div>
                              }
                           </div>
                        </div>
                        <div class="card-footer">
                           @Html.ActionLink("Détail du panier", "PanierDetail", "Client", new { id = articlesVendeur.Key.NoVendeur }, new { @class = "btn btn-primary" })
                           <!-- <a href="/Client/PanierDetail" class="btn btn-primary">Détail du panier</a>-->
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <hr />
         }
      </div>
      <h3>Les catégories</h3>
      @Html.Partial("Client/Categories", Model.lstEntreCategories)

   </main>
</div>

PetitesPuces/PetitesPuces/Views/Shared/Client/ProduitCatalogue.cshtml
@model PagedList.IPagedList<PetitesPuces.Models.PPProduits>

<div class="card-deck">
    @foreach (var produit in Model)
    {
        string strNomDiv = "divItems" + produit.NoProduit;

   <div id="@strNomDiv" class="card border-dark mb-3 p-1 sCardItemCatalogue sCardItemCatalogue">
      <a href="@Url.Action("ProduitDetaille", "Client", new { @numero = produit.NoProduit})" class="custom-card">
         <img class="card-img-top" src="~/Content/images/@Html.DisplayFor(x => produit.Photo)" alt="produit ...." style="max-height: 14rem; min-height: 14rem;">
         <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(x => produit.Nom)</h5>
            <p class="card-text">
                @Html.DisplayFor(x => produit.PrixDemande)$<br />
                @if (produit.DateVente.HasValue && DateTime.Now <= produit.DateVente.Value)
                {
                    var rabais = produit.PrixDemande - produit.PrixVente;
                    <small>rabais de @rabais.Value.ToString("0.00")$</small><br />
                    <small>jusqu'au @produit.DateVente.Value.ToString("yyyy-MM-dd")</small><br />
                }
                @if (produit.NombreItems > 0)
                {
                    <span id="spQqt">Quantité restant: @Html.DisplayFor(x => produit.NombreItems)</span>
                }
                else if (produit.NombreItems <= 0)
                {
                    <span id="spQqt">Quantité restant:<span class="badge badge-danger">Rupture de stock</span></span>
                }
                <br />
                <small>#@Html.DisplayFor(x => produit.NoProduit)</small><br />
                <small>Date création: @produit.DateCreation.Value.ToString("yyyy-MM-dd")</small>
            </p>
            <p class="text-right">
               <span class="badge badge-success">@Html.DisplayFor(x => produit.PPCategories.Description)</span>

               @if (produit.DateVente.HasValue && DateTime.Now <= produit.DateVente.Value)
               {
                  <br /><span class="badge badge-warning">Promotion</span>
               }
            </p>
         </div>
      </a>
      @if (ViewBag.Provenance == "Vendeur")
      {
         if ((produit.Disponibilité == false) && (produit.NombreItems == -1))
         {
            <div class="card-footer" style="width:100%">
               <div class="alert alert-warning" role="alert" style="text-align:center">
                  <strong>Produit retiré</strong>
               </div>
            </div>
         }
         else
         {
            <div class="card-footer btn-group" style="width:100%">
               <!--<button type="button" class="btn btn-outline-primary" title="modifier le produit"><span class="fas fa-edit"></span></button>-->
               <button type="button" class="btn btn-outline-primary" title="modifier le produit">@Html.ActionLink("    ", "ModifierProduit", "Vendeur", new { id = produit.NoProduit }, new { @class = "fas fa-edit" })</button>
               <button type="button" class="btn btn-outline-primary" title="supprimer le produit" onclick="supprimerProduit(@produit.NoProduit)"><span class="fas fa-trash"></span></button>
            </div>
         }
      }
      else
      {
         <div class="card-footer btn-group" style="width:100%;">
            <button type="button" class="btn btn-outline-primary" title="Commander le produit" value="@produit.NoProduit" onclick="$.VerificationDisponibilite(this.value, @produit.NombreItems)"><i class="fas fa-shopping-cart"></i></button>
         </div>
      }
   </div>
    }
</div>