PetitesPuces/PetitesPuces/Models/AccueilVendeurViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PetitesPuces.Models
{
   public class AccueilVendeurViewModel
   {
      public Dictionary<PPCommandes, List<PPDetailsCommandes>> lstCommandesNonTraites { get; set; }
      public PPHistoriquePaiements historique { get; set; }
      public IQueryable<IGrouping<PPClients,PPArticlesEnPanier>> lstClientPanier { get; set; }
      public int nbVisites { get; set; }
      public List<int> lstStatsClients { get; set; }

      //Constructeur pour la page d'accueil vendeur
      public AccueilVendeurViewModel(Dictionary<PPCommandes, List<PPDetailsCommandes>> lstCommandesNonTraites, IQueryable<IGrouping<PPClients, PPArticlesEnPanier>> lstClientPanier, int nbVisites)
      {
         this.lstCommandesNonTraites = lstCommandesNonTraites;
         this.lstClientPanier = lstClientPanier;
         this.nbVisites = nbVisites;
      }

      //Constructeur pour la page Detail Commande
      public AccueilVendeurViewModel(Dictionary<PPCommandes, List<PPDetailsCommandes>> lstCommandesNonTraites, PPHistoriquePaiements historique)
      {
         this.lstCommandesNonTraites = lstCommandesNonTraites;
         this.historique = historique;
      }
   }
}

PetitesPuces/PetitesPuces/Models/GestionProduitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PetitesPuces.Models
{
   public class GestionProduitViewModel
   {
      public PPProduits produit { get; set; }
      public HttpPostedFileBase file { get; set; }

      public GestionProduitViewModel()
      {
         
      }
   }
}

PetitesPuces/PetitesPuces/ViewModels/InformationPersonnelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PetitesPuces.ViewModels
{
    public class InformationPersonnelViewModel
    {
        public string AdresseCourriel { get; set; }
        public string Prenom { get; set; }
    }
}

PetitesPuces/PetitesPuces/Controllers/VendeurController.cs
using PetitesPuces.Models;
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Net;
using ExpertPdf.HtmlToPdf;
using System.Text;
using System.Web.UI;
using PetitesPuces.Filter;

namespace PetitesPuces.Controllers
{
    [VerifieSessionVendeur]
    public class VendeurController : Controller
    {
        DataClasses1DataContext contextPP = new DataClasses1DataContext();
        VendeurDao vendeurDao;

        public ActionResult Index() => RedirectToAction("AccueilVendeur");

        public ActionResult AccueilVendeur()
        {
            //A changer dans le futur pour la variable de session vendeur
            if (Session["vendeurObj"] == null)
            {
                return PartialView("index");
            }
            long noVendeur = (Session["vendeurObj"] as PPVendeurs).NoVendeur;
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            Dictionary<PPCommandes, List<PPDetailsCommandes>> lstDetailsProduitsCommandes = new Dictionary<PPCommandes, List<PPDetailsCommandes>>();
            //Aller chercher les commandes non traités
            var commandesNonTraite = (from commande in db.GetTable<PPCommandes>()
                                      where commande.NoVendeur.Equals((Session["vendeurObj"] as PPVendeurs).NoVendeur) && commande.Statut.Equals('N')
                                      orderby commande.DateCommande ascending
                                      select commande
                                      ).ToList();

            foreach (var commande in commandesNonTraite)
            {
                List<PPDetailsCommandes> lstDetailCommandes = new List<PPDetailsCommandes>();
                var query = (from detailsCommande in db.PPDetailsCommandes
                             where detailsCommande.NoCommande.Equals(commande.NoCommande)
                             select detailsCommande
                             ).ToList();
                lstDetailCommandes = query;
                lstDetailsProduitsCommandes.Add(commande, lstDetailCommandes);
            }

            //Aller chercher les paniers du vendeur
            var paniers = (from panier in db.GetTable<PPArticlesEnPanier>()
                           where panier.NoVendeur.Equals(noVendeur)
                           group panier by panier.PPClients
                           );

            //TODO : Aller chercher le nombres de visites quotidienne
            var visites = (from vendeurClient in db.GetTable<PPVendeursClients>()
                           where vendeurClient.NoVendeur.Equals(noVendeur)
                           select vendeurClient
                           ).ToList();

            //Aller chercher les clients actifs, potentiel et visiteurs du profil connecté.
            int nbClientsActif = 0;
            int nbClientsPotentiel = 0;
            int nbClientsVisiteurs = 0;

            var clients = (from c in db.GetTable<PPClients>()
                           select c
                           ).ToList();

            foreach (var client in clients)
            {
                var dejaCommande = (from commande in db.GetTable<PPCommandes>()
                                    where (commande.NoClient.Equals(client.NoClient)) &&
                                    (commande.NoVendeur.Equals(noVendeur))
                                    select commande
                             ).ToList();
                var possedePanier = (from panier in db.GetTable<PPArticlesEnPanier>()
                                     where (panier.NoClient.Equals(client.NoClient)) && (panier.NoVendeur.Equals(noVendeur))
                                     select panier
                                     ).ToList();

                if (dejaCommande.Count() > 0)
                {
                    nbClientsActif++;
                }
                else if (possedePanier.Count() > 0)
                {
                    nbClientsPotentiel++;
                }
                else
                {
                    nbClientsVisiteurs++;
                }
            }
            List<int> lstStats = new List<int>();
            lstStats.Add(nbClientsActif);
            lstStats.Add(nbClientsPotentiel);
            lstStats.Add(nbClientsVisiteurs);

            //Créer un object AccueilVendeurViewModel afin de l'envoyer a ma vue
            AccueilVendeurViewModel model = new AccueilVendeurViewModel(lstDetailsProduitsCommandes, paniers, visites.Count());
            model.lstStatsClients = lstStats;
            db.Connection.Close();

            return View(model);
        }

        public ActionResult AjouterProduit()
        {
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            var categories = (from cat in db.GetTable<PPCategories>()
                              select cat
                              ).ToList();

            ViewBag.ListeCategories = new SelectList(categories, "NoCategorie", "Description");

            PPProduits produit = new PPProduits();
            produit.Disponibilité = true;
            produit.NoVendeur = (Session["vendeurObj"] as PPVendeurs).NoVendeur;
            produit.NoCategorie = 70;

            GestionProduitViewModel gestionProduit = new GestionProduitViewModel();
            gestionProduit.produit = produit;

            ViewBag.Message = "";
            ViewBag.PrixVenteErreur = "";
            ViewBag.Action = "Ajouter";
            ViewBag.Form = "AjouterProduit";
            return View("GestionProduit", gestionProduit);
        }

        [HttpPost]
        public ActionResult AjouterProduit(GestionProduitViewModel model)
        {
            ViewBag.Message = "";
            ViewBag.PrixVenteErreur = "";
            List<string> parts = new List<string>();
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            //ValidateModel(model.produit);
            //Pour les dropdownlist aller voir le fichier : ---------> vers la ligne 300 du clientController et dans les InformationPersonel
            //TODO: Ajouter le produit dans la BASE DE DONNÉES
            PPProduits prod = model.produit;

            //Ajouter le produit dans la base de donnée
            if (ModelState.IsValid)
            {

                if (DateVentePrixVenteValide(model.produit.PrixVente, model.produit.DateVente))
                {
                    if ((model.produit.PrixDemande > model.produit.PrixVente) || (model.produit.PrixVente == null))
                    {

                        if (model.file != null && model.file.ContentLength > 0)
                            try
                            {
                                var postedFileExtension = Path.GetExtension(model.file.FileName);
                                //Validation si c'est un image 
                                if (!string.Equals(model.file.ContentType, "image/jpg", StringComparison.OrdinalIgnoreCase) &&
                                   !string.Equals(model.file.ContentType, "image/jpeg", StringComparison.OrdinalIgnoreCase) &&
                                   !string.Equals(model.file.ContentType, "image/pjpeg", StringComparison.OrdinalIgnoreCase) &&
                                   !string.Equals(model.file.ContentType, "image/gif", StringComparison.OrdinalIgnoreCase) &&
                                   !string.Equals(model.file.ContentType, "image/x-png", StringComparison.OrdinalIgnoreCase) &&
                                   !string.Equals(model.file.ContentType, "image/png", StringComparison.OrdinalIgnoreCase))
                                {
                                    ViewBag.Message("Le fichier doit être une image");
                                }
                                else if (!string.Equals(postedFileExtension, ".jpg", StringComparison.OrdinalIgnoreCase)
                                        && !string.Equals(postedFileExtension, ".png", StringComparison.OrdinalIgnoreCase)
                                        && !string.Equals(postedFileExtension, ".gif", StringComparison.OrdinalIgnoreCase)
                                        && !string.Equals(postedFileExtension, ".jpeg", StringComparison.OrdinalIgnoreCase))
                                {
                                    ViewBag.Message("Le fichier doit être une image");
                                }
                                //Le nom de l'image sur le serveur sera le numeros du produit + l'extension de l'image
                                if (!ViewBag.Message.Equals("Le fichier doit être une image"))
                                {
                                    parts = model.file.FileName.Split('.').Select(f => f.Trim()).ToList();

                                    var nbProduit = (from produits in db.GetTable<PPProduits>()
                                                     select prod
                                    ).ToList();
                                    //Le pattern de num produit va être à retravailler.
                                    //prod.NoProduit = (nbProduit.Count() + 1) * 10;
                                    var maxNoProduitVendeur = (from pMax in db.GetTable<PPProduits>()
                                                               where pMax.NoVendeur.Equals((Session["vendeurObj"] as PPVendeurs).NoVendeur)
                                                               select pMax
                                                               ).ToList();
                                    long noProduit;
                                    if (maxNoProduitVendeur.Count() > 0)
                                    {

PetitesPuces/PetitesPuces/Views/Vendeur/AjouterProduit.cshtml
@using PetitesPuces.Models
@model PPProduits
<!DOCTYPE html>

<html>
<head>
   <meta name="viewport" content="width=device-width" />
   <title>PetitesPuces</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
   <link rel="stylesheet" href="~/Content/css/styleGeneral.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
    @Html.Partial("index")
    <div class="container">
      @Html.Partial("Vendeur/FormulaireProduit",Model)
    </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Vendeur/CommandeDetail.cshtml
@using PetitesPuces.Models
@model AccueilVendeurViewModel
@{
   Layout = null;
}

<!DOCTYPE html>
<html>
<head>
   <meta name="viewport" content="width=device-width" />
   <title>Petites Puces</title>
   <!--Librairies externes (Bootstrap 4.2)-->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
   <link rel="stylesheet" href="~/Content/css/styleGeneral.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

   <script type="text/javascript">
      function accepter(id) {
         console.log($('#saisie_courriel').css("visibility") == "hidden");
         if ($('#saisie_courriel').css("visibility") == "hidden") {
            var objSaisieMessage = document.getElementById('saisie_courriel');
            objSaisieMessage.style.visibility = "visible";
            //var message = 'Bonjour M.  j\'ai l\'honneur de vous annoncer que votre demande de vendeur a été acceptée.';
            //$('#form_message').text(message);
            //$('#btn_accepter').prop("disabled", true);
            //$('#btn_refuser').prop("disabled", true);
            //var redevance = $('#redevance').val();
            //redevance = redevance.replace(",", ".");
            //redevance = parseFloat(redevance);

            /*$.ajax({
               url: "/Gestionnaire/AccepterVendeur",
               data: { "id": id, "redevance": redevance },
               success: success,
               error: error,
            });*/
         }
      }

      function confirmer(noExpediteur, noDestinataire) {
         //Aller chercher le message
         var message = $('#form_message').val();
         console.log('message: ' + message);
         if (message.trim() != '') {
            $.ajax({
               url: "/Vendeur/EnvoyerMessage",
               data: { "noDestinataire": noDestinataire, "noExpediteur": noExpediteur, "message": message },
               success: retourAccueil,
               error: error,
            });
         }
         else {
            console.log('écrit un message pour l\'envoyer');
            alert('Veuillez écrire un message.');
         }
      }

      function retourAccueil() {
         location.href = "/Vendeur/AccueilVendeur";
      }

      /*function success(model) {
          $("#panier").html(model)
          //console.log(model);
      }*/

      function error(error) {
         console.log('erreur : ' + error);
         //location.href = '/Client/AccueilClient';
      }
   </script>
</head>
<body>
   @Html.Partial("index")
   <br />
   <div class="container">

      @foreach (var commande in Model.lstCommandesNonTraites)
      {

         <h3>Détail commande: @commande.Key.NoCommande (Client: @commande.Key.PPClients.Prenom @commande.Key.PPClients.Nom)</h3>
         <br />
         <table class="table">
            <thead>
               <tr>
                  <th scope="col"># Produit</th>
                  <th scope="col">Nom</th>
                  <th scope="col">Quanité</th>
                  <th scope="col">Prix de vente</th>
                  <th scope="col">Prix total</th>
               </tr>
            </thead>
            <tbody>


               @foreach (var detailsCommande in commande.Value)
               {
                  double dblPrixVente = (double)detailsCommande.PrixVente;
                  double dblPrixTotal = dblPrixVente * (int)detailsCommande.Quantité;
                  <tr>
                     <td> @detailsCommande.PPProduits.NoProduit </td>
                     <td>@detailsCommande.PPProduits.Nom</td>
                     <td>@detailsCommande.Quantité</td>
                     <td>@dblPrixVente.ToString("0.00") $</td>
                     <td>@dblPrixTotal.ToString("0.00") $</td>
                  </tr>
               }
            </tbody>
         </table>
         //déclarations des nécessaire
         double dblMontantTotAvTaxes = (double)commande.Key.MontantTotAvantTaxes;
         double dblTPS = (double)commande.Key.TPS;
         double dblTVQ = (double)commande.Key.TVQ;
         double dblLivraison = (double)Model.historique.FraisLivraison;
         double dblPoids = (double)commande.Key.PoidsTotal;
         double dblRedevence = (double)Model.historique.Redevance;
         double dblFraisLesi = (double)Model.historique.FraisLesi;
         double dblPrixTotalTotal = dblMontantTotAvTaxes + dblTPS + dblTVQ + dblLivraison + dblFraisLesi;

         <hr />
         <br />
         <div class="row">
            <!--Informations sur les frais-->
            <div class="col-sm-6">
               <div class="card">
                  <div class="card-header">
                     <h4>Frais de commandes</h4>
                  </div>
                  <div class="card-body">
                     <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Prix Avant Taxe: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblMontantTotAvTaxes.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>TPS: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblTPS.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>TVQ: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblTVQ.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Frais de livraison: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblLivraison.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>

            <div class="col-sm-6">
               <div class="card">
                  <div class="card-header">
                     <h4>Informations Supplémentaires</h4>
                  </div>
                  <div class="card-body">
                     <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Poids: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblPoids (lbs)</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Type de livraison: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@commande.Key.PPTypesLivraison.Description</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Redevance: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblRedevence.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="list-group-item">
                           <div class="row">
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-start">
                                    <h6>Frais de Lesi: </h6>
                                 </div>
                              </div>
                              <div class="col-sm-6">
                                 <div class="d-flex justify-content-end">
                                    <h6>@dblFraisLesi.ToString("0.00") $</h6>
                                 </div>
                              </div>
                           </div>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
         <br />
         <h3>Prix Total: @dblPrixTotalTotal.ToString("0.00") $</h3>
         <hr />
         
         long noVendeur = (Session["vendeurObj"] as PPVendeurs).NoVendeur;
         
         <div class="row">
            <div class="col-sm-6">
               <button class="btn btn-primary" style="width: 100%" onclick="accepter(@noVendeur);">Envoyer un courriel au client</button>
            </div>
            <div class="col-sm-6">
               @Html.ActionLink("Livrer", "Livrer", "Vendeur", new { id = commande.Key.NoCommande }, new { @class = "btn btn-success", @style = "width:100%" })
               <!--<button class="btn btn-success" style="width : 100%">Livrer</button>-->
            </div>
         </div>
      }
      @{
         MessageViewModel message = new MessageViewModel((int)Model.lstCommandesNonTraites.First().Key.NoVendeur, (int)Model.lstCommandesNonTraites.First().Key.NoClient, ViewBag.NomVendeur, ViewBag.NomClient, "");
      }

      <div id="saisie_courriel" style="visibility:hidden">
         <br />
         <h4>Envoie d'un message</h4>
         @Html.Partial("Courriel/Message", message);
      </div>
   </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Vendeur/GestionProfileVendeur.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Gestion profile du vendeur</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
    <div>
        <label class="col-form-label">Nom d'affaire</label>
        <label class="col-form-label">Prénom</label>
        <label class="col-form-label">Nom</label>
        <label class="col-form-label">Rue</label>
        <label class="col-form-label">Ville</label>
        <label class="col-form-label">Province</label>
        <label class="col-form-label"></label>
        <label class="col-form-label"></label>
        <label class="col-form-label"></label>
        <label class="col-form-label"></label>
        <label class="col-form-label"></label>
        <label class="col-form-label"></label>
    </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Vendeur/InformationPersonnel.cshtml
@model PetitesPuces.Models.PPVendeurs

@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.NoVendeur)
    @Html.HiddenFor(x => x.AdresseEmail)
    @Html.Hidden("strProvenence", "")
    <div class="card">
        <h5 class="card-header">Modification du profil de <span>@Html.DisplayFor(model => Model.AdresseEmail)</span></h5>
        <div class="card-body">
            <div class="form-row form-group">
                <div class="col-3">
                    <label class="col-form-label">Prénom</label>
                    @Html.TextBoxFor(model => Model.Prenom, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Prenom)
                </div>
                <div class="col-3">
                    <label class="col-form-label">Nom</label>
                    @Html.TextBoxFor(model => Model.Nom, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Nom)
                </div>
                <div class="col-3">
                    <label class="col-form-label">Rue</label>
                    @Html.TextBoxFor(model => Model.Rue, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Rue)
                </div>
                <div class="col-3">
                    <label class="col-form-label">Ville</label>
                    @Html.TextBoxFor(model => Model.Ville, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Ville)
                </div>
            </div>
            <div class="form-row form-group">
                <div class="col-3">
                    <label class="col-form-label">Province</label>
                    @Html.DropDownListFor(x => x.Province, (SelectList)ViewBag.ListeProvinces, new { @class = "custom-select"})
                </div>
                <div class="col-3">
                    <label class="col-form-label">Pays</label>
                    @Html.TextBoxFor(x => x.Pays, new { @class = "form-control", @readonly = "readonly"})
                </div>
                <div class="col-2">
                    <label class="col-form-label">Code postal</label>
                    @Html.TextBoxFor(model => Model.CodePostal, new { @class = "form-control", placeholder = "A9A 9A9", @id = "codePostal" })
                    @Html.ValidationMessageFor(x => x.CodePostal)
                </div>
                <div class="col-2">
                    <label class="col-form-label">Téléphone #1</label>
                    @Html.TextBoxFor(model => Model.Tel1, new { @class = "form-control", placeholder = "(999) 999-9999", @id = "tel1" })
                    @Html.ValidationMessageFor(x => x.Tel1)
                </div>
                <div class="col-2">
                    <label class="col-form-label">Téléphone #2</label>
                    @Html.TextBoxFor(model => Model.Tel2, new { @class = "form-control", placeholder = "(999) 999-9999", @id = "tel2" })
                    @Html.ValidationMessageFor(x => x.Tel2)
                </div>
            </div>
        </div>
        <div class="card-footer btn-group sPiedPageBouton">
            <button type="submit" class="btn btn-outline-success" value="informationPersonnel" onclick="envoieSection(this)" >Sauvegarder</button>
            <a href="@Url.Action("/")" class="btn btn-outline-primary">Retour à l'accueil</a>
        </div>
    </div>
}