PetitesPuces/PetitesPuces/Controllers/InternauteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using PetitesPuces.Models;


namespace PetitesPuces.Controllers
{
    public class InternauteController : Controller
    {
        // GET: Inscription
        public ActionResult Index()
        {
            List<Models.EntrepriseCategorie> lstEntreCate = new List<Models.EntrepriseCategorie>();
            /* Compare data with Database */
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            var toutesCategories = (from cat in db.GetTable<Models.PPCategories>()
                                    select cat
               );
            foreach (var cat in toutesCategories)
            {
                List<PPVendeurs> lstVendeurs = new List<PPVendeurs>();
                var query = (from prod in db.GetTable<Models.PPProduits>()
                             where prod.NoCategorie.Equals(cat.NoCategorie)
                             select prod
                   );
                foreach (var item in query)
                {
                    if (!lstVendeurs.Contains(item.PPVendeurs))
                    {
                        lstVendeurs.Add(item.PPVendeurs);
                    }
                }
                lstEntreCate.Add(new Models.EntrepriseCategorie(cat, lstVendeurs));
            }
            return View("AccueilInternaute", lstEntreCate);
        }

        public ActionResult AccueilInternaute()
        {
            List<Models.EntrepriseCategorie> lstEntreCate = new List<Models.EntrepriseCategorie>();
            /* Compare data with Database */
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            var toutesCategories = (from cat in db.GetTable<Models.PPCategories>()
                                    select cat
                                    );
            foreach (var cat in toutesCategories)
            {
                List<PPVendeurs> lstVendeurs = new List<PPVendeurs>();
                var query = (from prod in db.GetTable<Models.PPProduits>()
                             where prod.NoCategorie.Equals(cat.NoCategorie)
                             select prod
                             );
                foreach (var item in query)
                {
                    if (!lstVendeurs.Contains(item.PPVendeurs))
                    {
                        lstVendeurs.Add(item.PPVendeurs);
                    }
                }
                lstEntreCate.Add(new Models.EntrepriseCategorie(cat, lstVendeurs));
            }
            return View(lstEntreCate);
        }

        public ActionResult CatalogueNouveaute()
        {
            Models.DataClasses1DataContext db = new Models.DataClasses1DataContext();
            db.Connection.Open();
            var nouveauProduit = (from prod in db.GetTable<Models.PPProduits>()
                                  orderby prod.DateCreation descending
                                  select prod
                                  ).ToList();
            db.Connection.Close();

            return View(nouveauProduit);
        }

        public ActionResult ProduitDetaille(long noProduit)
        {
            var model = new ViewModels.ProduitDetailViewModel();
            var dcontext = new DataClasses1DataContext();

            model.Produit = dcontext.PPProduits.FirstOrDefault(p => p.NoProduit == noProduit);
            model.nbEvaluateurs = dcontext.PPEvaluations.Count(x => x.NoProduit == model.Produit.NoProduit);

            if (model.nbEvaluateurs != 0)
            {
                //La moyenne des evaluations
                model.FormattedRating = Math.Round(dcontext.PPEvaluations
                    .Where(e => e.NoProduit == model.Produit.NoProduit).Average(x => x.Cote).Value, 1);
            }

            return View(model);
        }

        //GET
        public ActionResult Inscription()
        {

            var a = Session["vendeurObj"] as PPVendeurs;
            var b = Session["clientObj"] as PPClients;

            if (b != null)
            {
                var model = new PPClientViewModel()
                {
                    vendeur = new PPVendeurs()
                    {
                        Nom = b.Nom,
                        Prenom = b.Prenom,
                        Rue = b.Rue,
                        Ville = b.Ville,
                        Province = b.Province,
                        CodePostal = b.CodePostal,
                        Tel1 = b.Tel1,
                        Tel2 = b.Tel2
                    },
                    boolVendeur = true
                };
                return View(model); // return model de client
            }

            return View();
        }


        [HttpPost] //POST
        [ValidateAntiForgeryToken]
        public ActionResult Inscription(Models.PPClientViewModel model)
        {

            /* Variables required for client registration */
            var username = model.vendeur.AdresseEmail;
            var confUsername = model.confirmUsername;
            var password = model.vendeur.MotDePasse;
            var confPassword = model.confirmPassword;
            var clientSectionValid = (username != null && password != null);
            var usernameConfirmValid = username == confUsername;
            var passwordConfirmValid = password == confPassword;

            /* Variables required for seller registration */
            var etreVendeur = model.boolVendeur;

            //reset
            model.errorMessage = "";
            model.okMessage = "";

            /* Some validations */
            try
            {
                MailAddress ma = new MailAddress(username);
                if(ma.Address != username)
                    throw new Exception();
            }
            catch (Exception)
            {
                ModelState["vendeur.AdresseEmail"].Errors.Add("Le format de l'adresse courriel n'est pas valide !");
                model.errorMessage = " ";
            }

            if (!usernameConfirmValid)
            {
                ModelState[nameof(model.confirmUsername)].Errors.Add("Le deuxième courriel doit correspondre au premier.");
                model.errorMessage = " ";
            }

            if (!passwordConfirmValid)
            {
                ModelState[nameof(model.confirmPassword)].Errors.Add("Le deuxième mot de passe doit correspondre au premier.");
                model.errorMessage = " ";
            }

            if (!etreVendeur) // "Je veux etre vendeur" is not checked
            {
                //Clear errors in Vendeur section
                foreach (var item in ModelState.Keys.Where(s => !s.Equals("vendeur.AdresseEmail") &&
                        !s.Equals("vendeur.MotDePasse") && !s.Equals("confirmUsername") && !s.Equals("confirmPassword")))
                {
                    ModelState[item].Errors.Clear();
                }
            }

            /* Database section */
            var context = new DataClasses1DataContext();

            if (clientSectionValid && !etreVendeur && usernameConfirmValid && passwordConfirmValid)
            {
                //
                //Register client
                //
                try
                {
                    context.Connection.Open();
                }
                catch (Exception)
                {
                    model.errorMessage = "Connexion à la base de donnée échouée !";
                    return View(model);
                }

                var max = (context.PPClients.Max(x => x.NoClient) + 1);

                //Maximum amount of clients reached
                if (max >= 99999)
                    model.errorMessage = "Nous avons atteint le nombre maximum de vendeurs (100).";

                //Email exists             
                else if (context.PPClients.Any(x => x.AdresseEmail.ToLower().Equals(model.vendeur.AdresseEmail.ToLower())) ||
                        context.PPVendeurs.Any(x => x.AdresseEmail.ToLower().Equals(model.vendeur.AdresseEmail.ToLower())) ||
                        context.PPGestionnaire.Any(x => x.AdresseEmail.ToLower().Equals(model.vendeur.AdresseEmail.ToLower())))
                {
                    ModelState["vendeur.AdresseEmail"].Errors.Add("Ce courriel est déjà inscrit !");
                    model.errorMessage = " ";
                }

                //Stop right there if theres an error
                if (model.errorMessage != "") return View(model);

                //Transaction
                using (var transaction = new TransactionScope())
                {
                    try
                    {
                        context.PPClients.InsertOnSubmit(new PPClients()
                        {
                            NoClient = max > 10000 ? max : 10001,
                            AdresseEmail = model.vendeur.AdresseEmail,
                            MotDePasse = model.vendeur.MotDePasse,
                            Pays = "Canada",
                            DateCreation = DateTime.Now,
                            Statut = 1
                        });

                        context.SubmitChanges();
                        transaction.Complete();
                        ModelState.Clear();

                        context.Connection.Close();
                        return View(new PPClientViewModel() { okMessage = "Vous vous êtes inscrit comme client." });
                    }
                    catch (Exception ex)
                    {
                        model.errorMessage = "L'ajout dans la base de données a échoué. " + ex.Message;
                    }
                }

                context.Connection.Close();

            }

PetitesPuces/PetitesPuces/Views/Internaute/AccueilInternaute.cshtml
@using PetitesPuces.Models
@model List<EntrepriseCategorie>
<!DOCTYPE html>

<html>
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Petites Puces</title>

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

   <style>
      body {
         position: relative;
      }

      #navbarCategorie {
         position: fixed;
      }

      <style >
      /*
         * Base structure
         */
      /* Move down content because we have a fixed navbar that is 50px tall */
      /*
         body {
         padding-top: 50px;
      }
      */
      /*
         * Typography
         */
      h1 {
         margin-bottom: 20px;
         padding-bottom: 9px;
         border-bottom: 1px solid #eee;
      }

      /*
         * Sidebar
         */

      .sidebar {
         position: fixed;
         top: 51px;
         bottom: 0;
         left: 0;
         z-index: 1000;
         padding: 20px;
         overflow-x: hidden;
         overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
         border-right: 1px solid #eee;
      }

      /* Sidebar navigation */
      .sidebar {
         padding-left: 0;
         padding-right: 0;
      }

         .sidebar .nav {
            margin-bottom: 20px;
         }

         .sidebar .nav-item {
            width: 100%;
         }

            .sidebar .nav-item + .nav-item {
               margin-left: 0;
            }

         .sidebar .nav-link {
            border-radius: 0;
         }

      /*
         * Dashboard
         */

      /* Placeholders */
      .placeholders {
         padding-bottom: 3rem;
      }

      .placeholder img {
         padding-top: 1.5rem;
         padding-bottom: 1.5rem;
      }
   </style>

</head>
<body>
   <!--Barre de navigation-->
  @Html.Partial("index")

   <div class="container-fluid">
      <div class="row">
         <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            <h4>Les cat&eacute;gories</h4>
            <ul class="nav nav-pills flex-column">

               @foreach (var item in Model)
               {
                  if (item.lstVendeurs.Count() > 0)
                  {
                     <li class="nav-item">
                        <a class="nav-link" href="#headingCat_@item.categorie.NoCategorie">@item.categorie.Description<span class="sr-only">(current)</span></a>
                     </li>
                  }
               }
            </ul>
         </nav>

         <!--Les catégories avec entreprises-->
         <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            <div class="container">
               <br /><br />
               <hr />
               <h3>Les cat&eacute;gories</h3>
               <br />
               <!--Première catégorie-->
               @Html.Partial("Client/Categories", Model)
            </div>
         </main>

      </div>
   </div>

</body>
</html>

PetitesPuces/PetitesPuces/Views/Internaute/CatalogueNouveaute.cshtml
@using PetitesPuces.Models
@model List<PPProduits>
@{
   ViewBag.Title = "CatalogueNouveaute";
}

@{
   Layout = null;
}

<!DOCTYPE html>

<html>
<head>
   <meta name="viewport" content="width=device-width" />
   <title>Page Catalogue</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
   <link rel="stylesheet" href="~/Content/css/styleGeneral.css">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
   <style>
      .sCardItemCatalogue {
         max-width: 17rem;
         min-width: 17rem;
      }

      a.custom-card,
      a.custom-card:hover {
         color: inherit;
      }
   </style>
</head>
<body>
   @Html.Partial("index")
  <br />
   <div class="container">
      <br />
      <div class="alert alert-warning d-flex justify-content-center" role="alert">
         <h5>*Pour voir l'ensemble des produits et commander, vous devez vous connecter au système*</h5>
      </div>
      <br />
      <div class="card-columns">
         @for (int i = 0; (i < 15) && (i < Model.Count()); i++)
         {
            double dblPrixVente = (double)Model[i].PrixDemande;
            <!--<a href="/Internaute/ProduitDetaille" class="custom-card">-->
            <div id="divItems" class="card border-dark mb-3 sCardItemCatalogue">
               <img class="card-img-top" src="~/Content/images/@Model[i].Photo" alt="produit ...." width="250px" height="250px">
               <div class="card-body">
                  <h5 class="card-title">@Model[i].Nom</h5>
                  <p class="card-text">
                     <span id="spPrix">@dblPrixVente.ToString("0.00") $</span><br />
                     <span id="spQqt">Quantité restant: @Model[i].NombreItems</span><br />
                     <small>
                        #@Model[i].NoProduit
                     </small>
                  </p>
                  <p class="text-right"><span class="badge badge-success">@Model[i].PPCategories.Description</span></p>
                  <img src="~/Content/images/new_item.jpg" width="45px" height="45px">
                  @*Html.ActionLink("Détails du produit", "ProduitDetaille", "Internaute", new { noProduit = Model[i].NoProduit }, new { @class = "btn btn-primary"})*@
               </div>
            </div>
            <!--</a>-->
         }


      </div>
   </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Internaute/Inscription.cshtml
@model PetitesPuces.Models.PPClientViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inscription</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome (Icons) -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- JQuery mask -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>


    <script>
        $(document).ready(function () {
            $("#btnPasswordVisible").click(function () {
                $("#iconVisible").toggleClass("fa-eye fa-eye-slash");
                var newType = ($("#tbPassword").attr("type") === "password") ? "text" : "password";
                $("#tbPassword").attr("type", newType);
            });

            $("#btnPasswordVisible2").click(function () {
                $("#iconVisible2").toggleClass("fa-eye fa-eye-slash");
                var newType = ($("#tbPassword2").attr("type") === "password") ? "text" : "password";
                $("#tbPassword2").attr("type", newType);
            });

            $('#tbCodePostal').mask('S0S 0S0');
            $('#tbTel1').mask('(000) 000-0000');
            $('#tbTel2').mask('(000) 000-0000');
            $('#tbLivraisonGratuite').mask('000.00');

        });
    </script>
    <style>
        .tooltiptext {
            visibility: hidden;
            width: 220px;
            background-color: black;
            color: #fff;
            text-align: center;
            border-radius: 6px;
            padding: 5px;
            opacity: 0.85;
            /* Position the tooltip */
            position: absolute;
            z-index: 1;
            top: -5px;
            left: 105%;
        }

        .tooltiptexterror {
            visibility: hidden;
            width: fit-content;
            background-color: orangered;
            color: #fff;
            border-radius: 6px;
            opacity: 0.90;
            position: absolute;
            z-index: 1;
            top: 105%;
            left: 10px;
            text-align: left;
        }

        .tooltipB:hover .tooltiptext, .tooltipB:hover .tooltiptexterror {
            visibility: visible;
        }

        .alert {
            padding: 0;
            border: none;
            font-size: 18px;
            line-height: 40px;
        }

        .custom-control-lg .custom-control-label::before,
        .custom-control-lg .custom-control-label::after {
            top: 0.1rem !important;
            left: -2rem !important;
            width: 1.25rem !important;
            height: 1.25rem !important;
        }

        .custom-control-lg .custom-control-label {
            margin-left: 0.5rem !important;
            font-size: 1rem !important;
        }

        .input-validation-error {
            border: 1px solid #ff0000;
            background-color: white;
        }

        .validation-summary-valid {
            display: none;
        }
    </style>
</head>
<body>
    <div class="container" style="min-height: 100vh; margin-top:150px;margin-bottom:150px;">

        <!-- Card -->
        <div class="card mx-auto my-auto" style="width: 40rem; min-width: 50rem">
            <div class="card-body h-100">

                <h5 class="card-title text-center">Inscription</h5>
                <br />
                @using (Html.BeginForm("Inscription", "Internaute", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="container">
                        <!-- Email -->
                        <div class="input-group mb-3 tooltipB">
                            <div class="input-group-prepend">
                                <span class="input-group-text text-center" style="width: 45px">
                                    <i class="fa fa-at" aria-hidden="true"></i>
                                </span>
                            </div>
                            <span class="tooltiptexterror">@Html.ValidationMessageFor(x => x.vendeur.AdresseEmail)</span>
                            @Html.EditorFor(x => x.vendeur.AdresseEmail, new {
                           htmlAttributes = new {
                               @class = "form-control ",
                               @placeholder = "Inscrivez votre courriel",
                               @maxlength = 100
                           }
                       })

                        </div>

                        <!-- Confirm Email-->
                        <div class="input-group mb-3 tooltipB">
                            <div class="input-group-prepend">
                                <span class="input-group-text text-center" style="width: 45px">
                                    <i class="fa fa-at" aria-hidden="true"></i>
                                </span>
                            </div>
                            <span class="tooltiptexterror">@Html.ValidationMessageFor(x => x.confirmUsername)</span>
                            @Html.EditorFor(x => x.confirmUsername, new {
                           htmlAttributes = new
                           {
                               @class = "form-control",
                               @placeholder = "Inscrivez votre courriel une autre fois",
                               @maxlength = 100
                           }
                       })

                        </div>

                        <!-- Password -->
                        <div class="input-group mb-3 has-feedback tooltipB">
                            <div class="input-group-prepend">
                                <span class="input-group-text text-center" style="width: 45px">
                                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                            </div>
                            @Html.EditorFor(x => x.vendeur.MotDePasse, new {
                           htmlAttributes = new
                           {
                               @id = "tbPassword",
                               @class = "form-control",
                               @placeholder = "Inscrivez votre mot de passe",
                               @maxlength = 50
                           }
                       })
                            <span class="tooltiptexterror">@Html.ValidationMessageFor(x => x.vendeur.MotDePasse)</span>
                            <span class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" style="border:1px solid #ced4da;border-left:none" id="btnPasswordVisible">
                                    <i class="fa fa-eye form-control-feedback" id="iconVisible"></i>
                                </button>
                            </span>

                        </div>

                        <!-- Confirm Password-->
                        <div class="input-group mb-3 has-feedback tooltipB">
                            <div class="input-group-prepend">
                                <span class="input-group-text text-center" style="width: 45px">
                                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                                </span>
                            </div>
                            @Html.EditorFor(x => x.confirmPassword, new {
                           htmlAttributes = new
                           {
                               @id = "tbPassword2",
                               @class = "form-control",
                               @placeholder = "Inscrivez votre mot de passe une autre fois",
                               @maxlength = 50
                           }
                       })
                            <span class="tooltiptexterror">@Html.ValidationMessageFor(x => x.confirmPassword)</span>
                            <span class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" style="border:1px solid #ced4da;border-left:none" id="btnPasswordVisible2">
                                    <i class="fa fa-eye form-control-feedback" id="iconVisible2"></i>
                                </button>
                            </span>
                        </div>

                        <br />

                        <!-- Accordion for vendeur-->
                        <div class="card">
                            <div class="card-header">

                                <div class="custom-control-lg custom-control custom-checkbox ">
                                    @Html.CheckBoxFor(x => x.boolVendeur, new {
                                       @id ="cbVendeur", @class= "custom-control-input", data_toggle="collapse"
                                       ,data_target="#sectionVendeur", aria_expanded = Model?.boolVendeur ?? false } )
                                    <label class="custom-control-label " for="cbVendeur">
                                        <span style="font-weight:bold">Je veux être un vendeur</span>
                                    </label>
                                </div>
                            </div>
                            <div id="sectionVendeur" class="collapse @(Model != null && Model.boolVendeur ? "show" : "hide")" aria-labelledby="vendeurHeading">
                                <div class="card-body">
                                    @Html.Partial("~/Views/Internaute/partialVendeurInformations.cshtml", Model)
                                </div>
                            </div>
                        </div>


                        <br />
                        <br />
                        <!--<p style="color:red">@Html.ValidationSummary()</p>-->
                        <div class="alert alert-danger text-center">@Html.DisplayFor(x => x.errorMessage)</div>
                        <div class="alert alert-success text-center">@Html.DisplayFor(x => x.okMessage)</div>
                        <div>
                            <input type="submit" value="S'inscrire" class="btn btn-primary btn-block" />
                        </div>
                        <br />
                        <div>
                            <a href="/Connexion" style="text-decoration: none;">
                                <input type="button" value="Retour à la page de connexion" class="btn btn-primary btn-block" />
                            </a>
                        </div>
                        <hr />
                        <br />
                        <div>
                            <p>
                                <a href="/Connexion/RecupererMDP">
                                    Oublié votre mot de passe?
                                </a>
                            </p>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Internaute/ProduitDetaille.cshtml
@using PetitesPuces.ViewModels
@model ProduitDetailViewModel

@{
   Layout = null;
}
<!DOCTYPE html>

<html>
<head>
   <meta name="viewport" content="width=device-width" />
   <title>Page produit détaillé</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
   <style>
      .checked {
         color: orange;
      }
   </style>
</head>
<body>
   <div id="navigation">
      @RenderPage("~/Views/Internaute/index.cshtml")
   </div>
   <br /><br /><br />
   <div class="container">
      @Html.Partial("Client/DetailProduit",Model)
   </div>
</body>
</html>

PetitesPuces/PetitesPuces/Views/Internaute/index.cshtml
@{ 
   if (Session["vendeurObj"] != null)
   {
      Response.Redirect(Url.Action("AccueilVendeur", "Vendeur"));
   }
   else if (Session["clientObj"] != null)
   {
      Response.Redirect(Url.Action("AccueilClient", "Client"));
   }
   else if (Session["gestionnaireObj"] != null)
   {
      Response.Redirect(Url.Action("AccueilGestionnaire", "Gestionnaire"));
   }
}

<header class="navbar navbar-expand-lg navbar-light bg-light bd-navbar">
   <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/Internaute/AccueilInternaute">Petites Puces</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
               <a class="nav-link" href="/Internaute/Inscription">Inscription<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/Connexion/" id="navbarDropdown">
                  Connexion
               </a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/Connexion/RecupererMDP">
                  Mot de passe oubli&eacute;
               </a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="#"><i class="fas fa-arrow-left"></i>Retour</a>
            </li>
         </ul>
      </div>
   </nav>
</header>